# Generated by Django 4.2.1 on 2023-05-11 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("courses", "0001_initial"),
        ("student_profile", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Grade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "exam_type",
                    models.CharField(
                        choices=[
                            ("internal", "Internal"),
                            ("final", "Final"),
                            ("practical", "Practical"),
                        ],
                        max_length=20,
                    ),
                ),
                ("total_marks", models.IntegerField(default=100)),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "course_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courses.coursesession",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GradeRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("marks_obtained", models.FloatField()),
                ("has_passed", models.BooleanField(default=False)),
                (
                    "grade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="grades.grade"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="student_profile.studentprofile",
                    ),
                ),
            ],
        ),
    ]
