# Generated by Django 4.2.1 on 2023-05-27 09:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("grades", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="time",
            field=models.TimeField(
                default=datetime.datetime(2023, 5, 27, 15, 25, 52, 502398)
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="exam",
            name="date",
            field=models.DateField(),
        ),
    ]
