# Generated by Django 4.2.1 on 2023-05-11 15:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("student_profile", "0003_alter_studentprofile_symbol_number"),
        ("courses", "0001_initial"),
        ("grades", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Grade",
            new_name="Exam",
        ),
        migrations.RenameField(
            model_name="graderecord",
            old_name="grade",
            new_name="exam",
        ),
        migrations.AlterUniqueTogether(
            name="graderecord",
            unique_together={("exam", "student")},
        ),
    ]
