# Generated by Django 4.2.1 on 2023-05-27 09:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("grades", "0002_exam_time_alter_exam_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="pass_marks",
            field=models.IntegerField(default=45),
        ),
    ]
