# Generated by Django 4.2.1 on 2023-05-27 09:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("grades", "0003_exam_pass_marks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="graderecord",
            name="marks_obtained",
            field=models.IntegerField(),
        ),
    ]
