# Generated by Django 4.2.1 on 2023-07-06 06:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("grades", "0004_alter_graderecord_marks_obtained"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="graderecord",
            name="has_passed",
        ),
    ]
