# Generated by Django 4.2.1 on 2023-05-27 06:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("student_profile", "__first__"),
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="StudentCourses",
            new_name="StudentCourse",
        ),
    ]
