# Generated by Django 4.2.1 on 2023-05-11 14:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student_profile", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="symbol_number",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
