# Generated by Django 4.2.1 on 2023-05-11 14:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student_profile", "0002_studentprofile_symbol_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentprofile",
            name="symbol_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
